services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: aiphuser
      POSTGRES_PASSWORD: aiph1234pass
      POSTGRES_DB: aiphdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "35432:5432"

volumes:
  postgres_data: