"""initial migration

Revision ID: 6dbafc0f8be5
Revises: 
Create Date: 2025-05-16 20:19:42.557674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dbafc0f8be5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_members',
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=30), nullable=True),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('supervisor_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['supervisor_id'], ['team_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_members_email'), 'team_members', ['email'], unique=True)
    op.create_index(op.f('ix_team_members_id'), 'team_members', ['id'], unique=False)
    op.create_table('objectives',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('level', sa.Enum('ORGANIZATIONAL', 'DEPARTMENTAL', 'TEAM', 'INDIVIDUAL', name='objectivelevel'), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('parent_objective_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('NOT_STARTED', 'ON_TRACK', 'AT_RISK', 'DELAYED', 'ACHIEVED', 'ON_HOLD', 'CANCELLED', name='objectivestatus'), nullable=False),
    sa.Column('priority', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='objectivepriority'), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('target_completion_date', sa.Date(), nullable=False),
    sa.Column('actual_completion_date', sa.Date(), nullable=True),
    sa.Column('last_updated_date', sa.DateTime(), nullable=True),
    sa.Column('alignment_statement', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('confidentiality', sa.Enum('PUBLIC', 'INTERNAL', 'RESTRICTED', name='objectiveconfidentiality'), nullable=True),
    sa.Column('strategic_perspective', sa.Enum('FINANCIAL', 'CUSTOMER', 'INTERNAL_PROCESS', 'LEARNING_GROWTH', name='objectivestrategicperspective'), nullable=True),
    sa.Column('review_cadence', sa.Enum('MONTHLY', 'QUARTERLY', 'BI_ANNUALLY', 'ANNUALLY', name='objectivereviewcadence'), nullable=True),
    sa.Column('last_review_date', sa.Date(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['team_members.id'], ),
    sa.ForeignKeyConstraint(['parent_objective_id'], ['objectives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_objectives_id'), 'objectives', ['id'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('team_member_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['team_member_id'], ['team_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('progress_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('objective_id', sa.Integer(), nullable=False),
    sa.Column('progress_date', sa.Date(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['objective_id'], ['objectives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_progress_updates_id'), 'progress_updates', ['id'], unique=False)
    op.create_index(op.f('ix_progress_updates_objective_id'), 'progress_updates', ['objective_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_progress_updates_objective_id'), table_name='progress_updates')
    op.drop_index(op.f('ix_progress_updates_id'), table_name='progress_updates')
    op.drop_table('progress_updates')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_objectives_id'), table_name='objectives')
    op.drop_table('objectives')
    op.drop_index(op.f('ix_team_members_id'), table_name='team_members')
    op.drop_index(op.f('ix_team_members_email'), table_name='team_members')
    op.drop_table('team_members')
    # ### end Alembic commands ###
