"""cleanup type missmatch

Revision ID: e97883aa7fce
Revises: 801b3eaac50e
Create Date: 2025-05-18 15:47:46.333970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e97883aa7fce'
down_revision: Union[str, None] = '801b3eaac50e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('key_results',
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('target_value', sa.Float(), nullable=False),
    sa.Column('current_value', sa.Float(), nullable=False),
    sa.Column('start_value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('FUTURE', 'CURRENT', 'PAST', name='keyresultstatus'), nullable=False),
    sa.Column('complexity_level', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='keyresultcomplexitylevel'), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('objective_id', sa.Integer(), nullable=False),
    sa.Column('team_member_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['objective_id'], ['objectives.id'], ),
    sa.ForeignKeyConstraint(['team_member_id'], ['team_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_key_results_id'), 'key_results', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_key_results_id'), table_name='key_results')
    op.drop_table('key_results')
    # ### end Alembic commands ###
