name: Deploy to VPS

on:
  push:
    branches:
      - main # Or your release branch, e.g., 'release/*'
  # Or trigger on creating a release tag:
  # release:
  #   types: [published]

jobs:
  build_and_push_images:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login to Docker Hub (or GHCR)
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      # For GHCR:
      # - name: Login to GitHub Container Registry
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }} # GITHUB_TOKEN has package write permissions

      - name: Build and push Backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/aiph-backend:latest # For GHCR: ghcr.io/${{ github.repository_owner }}/my-app-backend:latest
          # You can use ${{ github.sha }} or a release tag for more specific versioning

      - name: Build and push Frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/aiph-frontend:latest # For GHCR: ghcr.io/${{ github.repository_owner }}/my-app-frontend:latest

